#!/bin/sh

# macOS でのみ UniformTypeIdentifiers フレームワークをリンク
case "$(uname -s)" in
  Darwin)
    EXTRA_LDFLAGS="-framework UniformTypeIdentifiers"
    ;;
  *)
    EXTRA_LDFLAGS=""
    ;;
esac

if [ -n "${EXTRA_LDFLAGS}" ] && [ -n "${CGO_LDFLAGS:-}" ]; then
  export CGO_LDFLAGS="${CGO_LDFLAGS} ${EXTRA_LDFLAGS}"
elif [ -n "${EXTRA_LDFLAGS}" ]; then
  export CGO_LDFLAGS="${EXTRA_LDFLAGS}"
fi

exec go "$@"
